---
# handlers file for dovecot
- name: start dovecot
  service:
    name: dovecot
    state: started

- name: stop dovecot
  service:
    name: dovecot
    state: stopped

- name: restart dovecot
  service:
    name: dovecot
    state: restarted