---

- hosts: all
  pre_tasks:
    - name: Touch mail.log
      file:
        path: "{{ item }}"
        owner: root
        group: adm
        mode: 0644
        state: touch
      with_items:
        - /var/log/mail.log
      changed_when: false

  roles:
    - dovecot
